# Copyright (c) 2023 Contributors to the Eclipse Foundation
# 
# This program and the accompanying materials are made available under the
# Apache Software License 2.0 which is available at:
# https://www.apache.org/licenses/LICENSE-2.0.
# 
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
